all:
 vars:
  ansible_connection: ssh
  ansible_user: ubuntu
  ansible_become: true
  ansible_ssh_private_key_file: ~/.ssh/id_rsa
  validate_hosts: false
  confluent_common_repository_debian_release_version: focal
  env: aws
zookeeper:
  hosts:
    ip-20-10-1-174.eu-west-3.compute.internal:
      ansible_host: ec2-13-38-46-112.eu-west-3.compute.amazonaws.com
    ip-20-10-2-110.eu-west-3.compute.internal:
      ansible_host: ec2-35-180-37-206.eu-west-3.compute.amazonaws.com
    ip-20-10-3-139.eu-west-3.compute.internal:
      ansible_host: ec2-35-180-225-85.eu-west-3.compute.amazonaws.com
kafka_broker:
  hosts:
    ip-20-10-1-203.eu-west-3.compute.internal:
      ansible_host: ec2-15-237-37-84.eu-west-3.compute.amazonaws.com
    ip-20-10-2-165.eu-west-3.compute.internal:
      ansible_host: ec2-35-180-173-245.eu-west-3.compute.amazonaws.com
    ip-20-10-3-161.eu-west-3.compute.internal:
      ansible_host: ec2-52-47-148-235.eu-west-3.compute.amazonaws.com
schema_registry:
  hosts:
    ip-20-10-2-167.eu-west-3.compute.internal:
      ansible_host: ec2-13-38-38-234.eu-west-3.compute.amazonaws.com
kafka_rest:
  hosts:
    ip-20-10-2-135.eu-west-3.compute.internal:
      ansible_host: ec2-13-37-231-179.eu-west-3.compute.amazonaws.com
ksql:
  hosts:
    ip-20-10-2-116.eu-west-3.compute.internal:
      ansible_host: ec2-13-38-19-115.eu-west-3.compute.amazonaws.com
    ip-20-10-2-73.eu-west-3.compute.internal:
      ansible_host: ec2-35-180-130-10.eu-west-3.compute.amazonaws.com
kafka_connect:
  hosts:
    ip-20-10-2-28.eu-west-3.compute.internal:
      ansible_host: ec2-15-237-125-21.eu-west-3.compute.amazonaws.com
control_center:
  hosts:
    ip-20-10-2-230.eu-west-3.compute.internal:
      ansible_host: ec2-13-38-99-225.eu-west-3.compute.amazonaws.com