all:
  vars:
    ansible_connection: ssh
    ansible_user: ubuntu
    ansible_become: true
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    validate_hosts: false
    confluent_common_repository_debian_release_version: focal
    #Enable JMX Exporter
    jmxexporter_enabled: true
    jolokia_enabled: true
    env: aws

zookeeper:
  hosts:
    
    ip-10-4-11-119.eu-west-3.compute.internal:
      ansible_host: ec2-13-38-24-239.eu-west-3.compute.amazonaws.com
    
kafka_broker:
  hosts:
    
    ip-10-4-11-209.eu-west-3.compute.internal:
      ansible_host: ec2-15-188-27-250.eu-west-3.compute.amazonaws.com
      kafka_broker_custom_properties:
        broker.rack: eu-west-3a
    
schema_registry:
  hosts:
    ip-10-4-12-32.eu-west-3.compute.internal:
      ansible_host: ec2-13-38-48-35.eu-west-3.compute.amazonaws.com
kafka_rest:
  hosts:
    ip-10-4-12-185.eu-west-3.compute.internal:
      ansible_host: ec2-15-237-58-16.eu-west-3.compute.amazonaws.com
ksql:
  hosts:
    
    ip-10-4-11-221.eu-west-3.compute.internal:
      ansible_host: ec2-15-236-43-181.eu-west-3.compute.amazonaws.com
      
kafka_connect:
  hosts:
    ip-10-4-12-244.eu-west-3.compute.internal:
      ansible_host: ec2-13-36-239-156.eu-west-3.compute.amazonaws.com
control_center:
  hosts:
    ip-10-4-12-227.eu-west-3.compute.internal:
      ansible_host: ec2-15-237-109-26.eu-west-3.compute.amazonaws.com
