# Run playbook ~/cp-ansible/roles/confluent.test/molecule/ldap.yml
#   to create LDAP server
ldaps_enabled: true
ldaps_custom_certs: true
ssl_custom_certs: true
ssl_ca_cert_filepath: "{{ inventory_dir }}/../certs/generated_ssl_files/ca.crt"
ssl_signed_cert_filepath: "{{ inventory_dir }}/../certs/generated_ssl_files/{{inventory_hostname}}-ca1-signed.crt"
ssl_key_filepath: "{{ inventory_dir }}/../certs/generated_ssl_files/{{inventory_hostname}}-key.pem"

ldap_admin_password: "{{ vault_ldap_admin_password }}"

ldap_rbac_group: rbac
ldap_dc: example
ldap_dc_extension: com

ldap_users:
  - username: "{{kafka_broker_ldap_user}}"
    password: "{{kafka_broker_ldap_password}}"
    uid: 9999
    guid: 99
  - username: "{{schema_registry_ldap_user}}"
    password: "{{schema_registry_ldap_password}}"
    uid: 9998
    guid: 98
  - username: "{{kafka_connect_ldap_user}}"
    password: "{{kafka_connect_ldap_password}}"
    uid: 9997
    guid: 97
  - username: "{{ksql_ldap_user}}"
    password: "{{ksql_ldap_password}}"
    uid: 9996
    guid: 96
  - username: "{{control_center_ldap_user}}"
    password: "{{control_center_ldap_password}}"
    uid: 9995
    guid: 95
  - username: "{{kafka_rest_ldap_user}}"
    password: "{{kafka_rest_ldap_password}}"
    uid: 9994
    guid: 94
  - username: "{{mds_super_user}}"
    password: "{{mds_super_user_password}}"
    uid: 9993
    guid: 93
  - username: user1
    password: "{{ vault_user1_password }}"
    uid: 9992
    guid: 92
